language: node_js
node_js:
  - "10"

services:
  - docker

notifications:
  webhooks: http://185.255.79.67

cache: yarn

before_install:
  - cd web
  - yarn
  - yarn build
  - cd ../
  - docker-compose up -d

script:
  - git clone https://github.com/AM-NiceDay/darkside-tests.git
  - cd darkside-tests
  - yarn
  - yarn e2e
