language: node_js
node_js:
  - "10"

services:
  - docker

notifications:
  webhooks: http://185.255.79.67

cache: yarn

script:
  - cd web
  - yarn
  - yarn build
  - docker build -t testing/web .
  - docker run -d -p 80:80 testing/web
  - cd ../
  - git clone https://github.com/AM-NiceDay/darkside-tests.git
  - cd darkside-tests
  - yarn
  - yarn e2e
