language: node_js
node_js:
  - "10"

services:
  - docker

notifications:
  webhooks: http://185.255.79.67

cache: yarn

before_install:
  - cd web
  - yarn
  - yarn build
  - docker build -t testing/web .
  - docker run -d -p 80:80 testing/web

script:
  - yarn test:e2e
